// ================================================================
// MEGA COURSE SEEDER — 300+ courses
// School (Class 7-12) + JEE/NEET + University + Professional
// 
// Usage:  node seedMegaCourses.js
// Place in: backend/seedMegaCourses.js
// ================================================================

require("dotenv").config();
const mongoose = require("mongoose");
const Course = require("./models/Course");

const MONGO_URI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.DB_URI;

// ── Verified YouTube video IDs by subject ────────────────────────
const V = {
  // School subjects
  math7:      "NybHckSEQBI", math8:  "NybHckSEQBI", math9:  "NybHckSEQBI",
  math10:     "NybHckSEQBI", math11: "WUvTyaaNkzM", math12: "WUvTyaaNkzM",
  science7:   "URUJD5NEXC8", science8:"URUJD5NEXC8", science9:"URUJD5NEXC8",
  science10:  "URUJD5NEXC8",
  physics11:  "b1t41Q3xRM8", physics12:"b1t41Q3xRM8",
  chem11:     "bka20Q9TN6M", chem12: "bka20Q9TN6M",
  bio11:      "URUJD5NEXC8", bio12:  "URUJD5NEXC8",
  english:    "0G3_kG5FFfQ", hindi:  "2Sj6EMtHYkc",
  sst:        "wOclF9eP5OM", history:"Yocja_N5s1I",
  geography:  "PUB0TaZ7bhA", polsci: "nu_pCVPKzTk",
  accounts:   "vmEHCJofslg", business:"ua-CiDNNj30",
  economics:  "xxpc-HPKN28", cs:     "kqtD5dpn9C8",
  // JEE/NEET
  jee:        "tPYj3fFJGjk", neet:   "GwIo3gDZCVQ",
  // Professional
  python:     "kqtD5dpn9C8", js:     "W6NZfCO5SIk",
  react:      "w7ejDZ8SWv8", node:   "fBNz5xF-Kx4",
  java:       "eIrMbAQSU34", cpp:    "vLnPwxZdW4Y",
  ml:         "GwIo3gDZCVQ", dl:     "tPYj3fFJGjk",
  ds:         "vmEHCJofslg", webdev: "nu_pCVPKzTk",
  design:     "c9Wg6Cb_YlU", figma:  "FTFaQWZBqQ8",
  marketing:  "ua-CiDNNj30", sql:    "xxpc-HPKN28",
  cloud:      "W6NZfCO5SIk", devops: "fBNz5xF-Kx4",
  calculus:   "WUvTyaaNkzM", stats:  "xxpc-HPKN28",
  general:    "W6NZfCO5SIk",
};

// Helper to build videoUrl and thumbnail from ID
const t = (id) => ({
  videoUrl:  `https://www.youtube.com/embed/${V[id] || V.general}`,
  thumbnail: `https://img.youtube.com/vi/${V[id] || V.general}/maxresdefault.jpg`,
});

// ── ALL COURSES ──────────────────────────────────────────────────
const ALL_COURSES = [

  // ════════════════════════════════════════════════════════════════
  // CLASS 7 — ALL SUBJECTS
  // ════════════════════════════════════════════════════════════════
  { title:"Class 7 Mathematics — Integers", description:"Learn integers, properties of integers, operations on integers and number line representation as per NCERT Class 7.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 30m", ...t("math7"), whatYouLearn:["Introduction to integers","Addition of integers","Subtraction of integers","Multiplication of integers","Division of integers","Properties of integers"], quiz:[] },
  { title:"Class 7 Mathematics — Fractions and Decimals", description:"Master fractions and decimals with NCERT Class 7 — operations, comparisons, and real-life applications fully explained.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 00m", ...t("math7"), whatYouLearn:["Types of fractions","Multiplication of fractions","Division of fractions","Decimal operations","Converting fractions to decimals","Word problems"], quiz:[] },
  { title:"Class 7 Mathematics — Simple Equations", description:"Understand how to form and solve simple linear equations from word problems as per Class 7 NCERT Mathematics.", instructor:"Magnet Brains", category:"Mathematics", duration:"1h 30m", ...t("math7"), whatYouLearn:["What is an equation","Forming equations","Solving simple equations","Transposition method","Applications","Word problems"], quiz:[] },
  { title:"Class 7 Mathematics — Lines and Angles", description:"Study lines, angles, parallel lines, transversals and their properties as per NCERT Class 7 Geometry.", instructor:"Magnet Brains", category:"Mathematics", duration:"1h 45m", ...t("math7"), whatYouLearn:["Types of angles","Complementary and supplementary angles","Adjacent and vertically opposite angles","Parallel lines","Transversal and angle pairs","Properties"], quiz:[] },
  { title:"Class 7 Mathematics — Triangles", description:"Explore properties of triangles including angle sum property, exterior angle and Pythagoras theorem as per Class 7 NCERT.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 00m", ...t("math7"), whatYouLearn:["Triangle and its properties","Angle sum property","Exterior angle property","Congruence basics","Altitude and median","Pythagoras theorem intro"], quiz:[] },
  { title:"Class 7 Mathematics — Data Handling", description:"Learn data collection, organisation, bar graphs, pie charts, mean, median and mode for Class 7 Mathematics NCERT.", instructor:"Magnet Brains", category:"Mathematics", duration:"1h 30m", ...t("math7"), whatYouLearn:["Collecting and organising data","Mean, median and mode","Bar graphs","Double bar graphs","Pie charts","Probability basics"], quiz:[] },
  { title:"Class 7 Science — Nutrition in Plants", description:"Understand how plants prepare their food through photosynthesis, modes of nutrition in plants as per NCERT Class 7.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science7"), whatYouLearn:["Autotrophic nutrition","Photosynthesis process","Heterotrophic nutrition","Saprotrophic plants","Parasitic plants","Insectivorous plants"], quiz:[] },
  { title:"Class 7 Science — Nutrition in Animals", description:"Study how different animals digest food — from simple organisms to human digestive system as per NCERT Class 7.", instructor:"LearnoHub", category:"Science", duration:"1h 45m", ...t("science7"), whatYouLearn:["Modes of taking food","Digestion in amoeba","Digestion in grasshopper","Human digestive system","Absorption and assimilation","Diarrhoea and its prevention"], quiz:[] },
  { title:"Class 7 Science — Heat and Temperature", description:"Learn about heat, temperature measurement, conduction, convection and radiation with everyday examples for Class 7.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science7"), whatYouLearn:["Difference between heat and temperature","Thermometer and its types","Transfer of heat — conduction","Convection in fluids","Radiation","Land breeze and sea breeze"], quiz:[] },
  { title:"Class 7 Science — Acids Bases and Salts", description:"Understand properties of acids, bases and salts, indicators, neutralisation reactions as per NCERT Class 7 Science.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science7"), whatYouLearn:["Properties of acids","Properties of bases","Natural indicators","Neutralisation reaction","Uses of acids and bases","Everyday examples"], quiz:[] },
  { title:"Class 7 Science — Weather Climate and Adaptations", description:"Study weather vs climate differences, climatic zones and animal adaptations to different environments for Class 7.", instructor:"LearnoHub", category:"Science", duration:"1h 15m", ...t("science7"), whatYouLearn:["Weather and its elements","Climate definition","Polar region climate","Tropical rainforest climate","Animal adaptations","Migration"], quiz:[] },
  { title:"Class 7 Science — Motion and Time", description:"Learn about motion, types of motion, speed and measuring time with graphs and practical examples for NCERT Class 7.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science7"), whatYouLearn:["Types of motion","Slow and fast motion","Speed formula","Distance-time graph","Uniform motion","Measuring time"], quiz:[] },
  { title:"Class 7 English — Grammar Mastery", description:"Complete Class 7 English Grammar covering tenses, voice, reported speech, adjectives, adverbs and composition writing.", instructor:"Edumantra", category:"Language", duration:"3h 00m", ...t("english"), whatYouLearn:["Parts of speech","Tenses revision","Active and passive voice","Direct and indirect speech","Adjectives and adverbs","Essay and letter writing"], quiz:[] },
  { title:"Class 7 Hindi — Vyakaran (Grammar)", description:"Complete Class 7 Hindi Vyakaran covering sangya, sarvnam, visheshan, kriya, kaal and composition writing skills.", instructor:"Magnet Brains", category:"Language", duration:"3h 00m", ...t("hindi"), whatYouLearn:["Sangya aur sarvnam","Visheshan","Kriya aur kaal","Vachya","Muhavare","Anuched lekhan"], quiz:[] },
  { title:"Class 7 Social Science — Medieval India", description:"Study the rise of new kingdoms, Cholas, Delhi Sultanate and Mughal Empire in Medieval India for Class 7 History NCERT.", instructor:"Magnet Brains", category:"History", duration:"3h 00m", ...t("sst"), whatYouLearn:["New kings and kingdoms","Delhi Sultanate","Mughal Empire basics","Architecture of Medieval India","Bhakti movement","Regional cultures"], quiz:[] },
  { title:"Class 7 Social Science — Our Environment", description:"Explore Class 7 Geography covering environment types, biosphere, land, water and natural vegetation as per NCERT.", instructor:"Magnet Brains", category:"History", duration:"2h 30m", ...t("geography"), whatYouLearn:["Our environment","Biosphere","Land resources","Agriculture","Water resources","Natural vegetation and wildlife"], quiz:[] },
  { title:"Class 7 Social Science — Civics", description:"Understand democracy, state government, gender equality and markets as per NCERT Class 7 Social and Political Life.", instructor:"Magnet Brains", category:"History", duration:"2h 00m", ...t("polsci"), whatYouLearn:["Democracy and equality","State government working","Gender and equality","Understanding media","Markets around us","Role of market in economy"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // CLASS 8 — ALL SUBJECTS
  // ════════════════════════════════════════════════════════════════
  { title:"Class 8 Mathematics — Rational Numbers", description:"Understand rational numbers, their properties, representation on number line and operations as per NCERT Class 8.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 00m", ...t("math8"), whatYouLearn:["Introduction to rational numbers","Properties of rational numbers","Representation on number line","Operations on rational numbers","Between two rational numbers","Applications"], quiz:[] },
  { title:"Class 8 Mathematics — Linear Equations", description:"Learn to solve linear equations in one variable with NCERT Class 8 — applications and word problems included.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 00m", ...t("math8"), whatYouLearn:["Linear equation basics","Solving equations","Equations with variables on both sides","Reducing equations","Applications","Word problems"], quiz:[] },
  { title:"Class 8 Mathematics — Mensuration", description:"Calculate area and perimeter of polygons, surface areas and volumes of 3D shapes as per NCERT Class 8 Mensuration.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 30m", ...t("math8"), whatYouLearn:["Area of trapezium","Area of polygon","Solid shapes","Surface area of cube and cuboid","Surface area of cylinder","Volume of shapes"], quiz:[] },
  { title:"Class 8 Mathematics — Exponents and Powers", description:"Master exponents, laws of exponents and their applications in expressing large and small numbers for Class 8.", instructor:"Magnet Brains", category:"Mathematics", duration:"1h 30m", ...t("math8"), whatYouLearn:["Powers with negative exponents","Laws of exponents","Expressing as power of 10","Scientific notation","Comparing large numbers","Applications"], quiz:[] },
  { title:"Class 8 Mathematics — Factorisation", description:"Learn factorisation of algebraic expressions using common factors, regrouping, identities as per NCERT Class 8.", instructor:"Magnet Brains", category:"Mathematics", duration:"2h 00m", ...t("math8"), whatYouLearn:["Factors of natural numbers","Factors of algebraic expressions","Method of common factors","Factorisation by regrouping","Factorisation using identities","Division of algebraic expressions"], quiz:[] },
  { title:"Class 8 Science — Chemical Effects of Current", description:"Study electric current, conductors, insulators, electroplating and chemical effects of current for Class 8 Science.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science8"), whatYouLearn:["Conductors and insulators","LED and tester","Chemical effects of current","Electrolysis basics","Electroplating","Applications of electroplating"], quiz:[] },
  { title:"Class 8 Science — Light", description:"Understand reflection, laws of reflection, regular and diffused reflection, multiple reflections and human eye for Class 8.", instructor:"LearnoHub", category:"Science", duration:"1h 45m", ...t("science8"), whatYouLearn:["Laws of reflection","Regular and diffused reflection","Reflected light","Multiple reflections","Kaleidoscope","Human eye structure"], quiz:[] },
  { title:"Class 8 Science — Stars and the Solar System", description:"Explore stars, constellations, solar system, planets, satellites, comets and asteroids as per NCERT Class 8 Science.", instructor:"LearnoHub", category:"Science", duration:"2h 00m", ...t("science8"), whatYouLearn:["Stars and constellations","Solar system overview","The Moon","The Sun","Planets of solar system","Comets, asteroids and meteors"], quiz:[] },
  { title:"Class 8 Science — Pollution of Air and Water", description:"Study types of air and water pollution, causes, effects and methods of prevention as per NCERT Class 8 Science.", instructor:"LearnoHub", category:"Science", duration:"1h 30m", ...t("science8"), whatYouLearn:["Air pollution causes","Effects of air pollution","Greenhouse effect","Water pollution causes","Effects of water pollution","Potable water and purification"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // CLASS 9 — CHAPTER-WISE
  // ════════════════════════════════════════════════════════════════
  { title:"Class 9 Mathematics — Number Systems", description:"Complete Number Systems chapter for Class 9 — real numbers, irrational numbers, representing on number line and laws of exponents.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math9"), whatYouLearn:["Natural and whole numbers","Integers and rational numbers","Irrational numbers","Real numbers on number line","Operations on real numbers","Laws of exponents"], quiz:[] },
  { title:"Class 9 Mathematics — Polynomials", description:"Master polynomials — definitions, zeroes, remainder theorem, factor theorem and algebraic identities for Class 9.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 30m", ...t("math9"), whatYouLearn:["Polynomials in one variable","Zeroes of polynomial","Remainder theorem","Factor theorem","Algebraic identities","Factorisation of polynomials"], quiz:[] },
  { title:"Class 9 Mathematics — Coordinate Geometry", description:"Understand Cartesian system, plotting points, distance between points and quadrants as per NCERT Class 9.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 00m", ...t("math9"), whatYouLearn:["Cartesian system","Plotting a point","Quadrants","x-axis and y-axis","Coordinate of a point","Distance from axes"], quiz:[] },
  { title:"Class 9 Mathematics — Triangles", description:"Study congruence of triangles, criteria for congruence and inequalities in triangles as per NCERT Class 9.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math9"), whatYouLearn:["Congruence of triangles","Criteria: SAS, ASA, SSS, RHS","Properties of isosceles triangle","Inequalities in triangles","Angle sum property","Practical applications"], quiz:[] },
  { title:"Class 9 Mathematics — Statistics", description:"Learn data collection, frequency distribution, bar graphs, histogram, frequency polygon and mean/median/mode for Class 9.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("stats"), whatYouLearn:["Collection of data","Frequency distribution table","Bar graph and histogram","Frequency polygon","Mean of ungrouped data","Median and mode"], quiz:[] },
  { title:"Class 9 Science — Matter in Our Surroundings", description:"Study states of matter, properties, interconversion and effect of temperature and pressure on matter for Class 9.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("science9"), whatYouLearn:["Characteristics of matter","States of matter","Solid, liquid and gas properties","Evaporation","Boiling and melting","Effect of temperature on state"], quiz:[] },
  { title:"Class 9 Science — Is Matter Around Us Pure?", description:"Understand pure substances and mixtures, separation techniques, elements and compounds as per NCERT Class 9.", instructor:"Physics Wallah", category:"Science", duration:"2h 00m", ...t("science9"), whatYouLearn:["Mixtures and pure substances","Homogeneous and heterogeneous","Methods of separation","Evaporation and distillation","Elements and compounds","Colloids"], quiz:[] },
  { title:"Class 9 Science — Atoms and Molecules", description:"Learn laws of chemical combination, atomic theory, atomic mass, molecules and formulae for Class 9 Science.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("science9"), whatYouLearn:["Laws of chemical combination","Dalton's atomic theory","Atomic and molecular mass","Mole concept","Chemical formulae","Calculating molecular mass"], quiz:[] },
  { title:"Class 9 Science — Structure of the Atom", description:"Study Thomson and Rutherford models, Bohr model, atomic structure, valency and atomic number for Class 9.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("science9"), whatYouLearn:["Charged particles in matter","Thomson model","Rutherford model","Bohr model of atom","Atomic number and mass number","Valency"], quiz:[] },
  { title:"Class 9 Science — Tissues", description:"Understand plant and animal tissues, types and functions as per NCERT Class 9 Biology.", instructor:"Biomentors", category:"Science", duration:"2h 30m", ...t("bio11"), whatYouLearn:["Are plants and animals same?","Plant tissues: meristematic","Permanent tissues in plants","Animal tissues","Epithelial tissue","Connective, muscular and nervous tissue"], quiz:[] },
  { title:"Class 9 Science — The Fundamental Unit of Life", description:"Explore cell structure, organelles, plant vs animal cell, osmosis and diffusion for NCERT Class 9 Biology.", instructor:"Biomentors", category:"Science", duration:"2h 00m", ...t("bio11"), whatYouLearn:["What is a cell?","Structural organisation of cell","Plasma membrane","Cell wall","Nucleus","Organelles of cell"], quiz:[] },
  { title:"Class 9 Science — Motion", description:"Learn displacement, velocity, acceleration, equations of motion and graphical representation for Class 9 Physics.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Distance and displacement","Speed and velocity","Acceleration","Equations of motion","Graphical representation","Circular motion"], quiz:[] },
  { title:"Class 9 Science — Force and Laws of Motion", description:"Study Newton's three laws of motion, inertia, momentum and conservation of momentum for NCERT Class 9.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("physics11"), whatYouLearn:["Balanced and unbalanced forces","Newton's first law — inertia","Newton's second law — F=ma","Newton's third law","Conservation of momentum","Applications"], quiz:[] },
  { title:"Class 9 Science — Gravitation", description:"Understand universal law of gravitation, free fall, weight, mass, thrust and pressure as per NCERT Class 9 Science.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("physics11"), whatYouLearn:["Universal law of gravitation","Importance of law","Free fall","Mass and weight","Thrust and pressure","Archimedes principle"], quiz:[] },
  { title:"Class 9 Science — Work and Energy", description:"Learn scientific definition of work, kinetic and potential energy, law of conservation of energy and power for Class 9.", instructor:"Physics Wallah", category:"Science", duration:"2h 00m", ...t("physics11"), whatYouLearn:["Work done by force","Work done against gravity","Energy forms","Kinetic energy","Potential energy","Conservation of energy"], quiz:[] },
  { title:"Class 9 Science — Sound", description:"Study production and propagation of sound, characteristics, reflection, echo and range of hearing for Class 9 Science.", instructor:"Physics Wallah", category:"Science", duration:"2h 00m", ...t("physics11"), whatYouLearn:["Production of sound","Propagation of sound","Characteristics of sound","Reflection of sound","Echo","Range of hearing and SONAR"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // CLASS 10 — CHAPTER-WISE
  // ════════════════════════════════════════════════════════════════
  { title:"Class 10 Mathematics — Real Numbers", description:"Complete Real Numbers chapter with Euclid's division lemma, HCF, LCM, irrational numbers and decimal expansions.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math10"), whatYouLearn:["Euclid's division lemma","Fundamental theorem of arithmetic","HCF and LCM using prime factorisation","Irrational numbers proof","Rational numbers decimal expansion","Terminating vs non-terminating"], quiz:[] },
  { title:"Class 10 Mathematics — Polynomials", description:"Study polynomials, zeroes and coefficients relationship, division algorithm for Class 10 NCERT Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 00m", ...t("math10"), whatYouLearn:["Geometrical meaning of zeroes","Relationship between zeroes and coefficients","Division algorithm for polynomials","Quadratic polynomials","Cubic polynomials","Practical problems"], quiz:[] },
  { title:"Class 10 Mathematics — Pair of Linear Equations", description:"Solve pair of linear equations in two variables using graphical, substitution, elimination and cross-multiplication methods.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math10"), whatYouLearn:["Graphical method of solution","Substitution method","Elimination method","Cross-multiplication method","Equations reducible to linear form","Word problems"], quiz:[] },
  { title:"Class 10 Mathematics — Quadratic Equations", description:"Learn quadratic equations, solutions by factorisation and quadratic formula, discriminant and nature of roots for Class 10.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math10"), whatYouLearn:["Standard form of quadratic equation","Solution by factorisation","Completing the square","Quadratic formula","Discriminant","Nature of roots"], quiz:[] },
  { title:"Class 10 Mathematics — Arithmetic Progressions", description:"Understand AP, general term, sum of n terms and applications of arithmetic progressions for Class 10.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math10"), whatYouLearn:["Arithmetic progression definition","General term formula","nth term of AP","Sum of n terms","Applications of AP","Word problems"], quiz:[] },
  { title:"Class 10 Mathematics — Triangles", description:"Study similar triangles, criteria for similarity, areas and Pythagoras theorem proofs for Class 10 NCERT.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math10"), whatYouLearn:["Similar figures","Similarity of triangles","Criteria: AA, SSS, SAS","Areas of similar triangles","Pythagoras theorem","Converse of Pythagoras theorem"], quiz:[] },
  { title:"Class 10 Mathematics — Coordinate Geometry", description:"Learn distance formula, section formula, area of triangle using coordinates as per NCERT Class 10 Coordinate Geometry.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math10"), whatYouLearn:["Distance formula","Section formula","Midpoint formula","Area of triangle","Collinearity of points","Applications"], quiz:[] },
  { title:"Class 10 Mathematics — Introduction to Trigonometry", description:"Master trigonometric ratios, identities, complementary angles and practical applications for Class 10 NCERT.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math10"), whatYouLearn:["Trigonometric ratios","Ratios of complementary angles","Trigonometric identities","Values at 0°,30°,45°,60°,90°","Applications","Important identities"], quiz:[] },
  { title:"Class 10 Mathematics — Circles", description:"Study tangents, number of tangents from external point and properties of tangents for Class 10 NCERT Circles.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 00m", ...t("math10"), whatYouLearn:["Tangent to a circle","Number of tangents from a point","Theorem: tangent perpendicular to radius","Length of tangent","Two tangents from external point","Practical problems"], quiz:[] },
  { title:"Class 10 Science — Chemical Reactions and Equations", description:"Learn writing and balancing chemical equations, types of reactions for Class 10 NCERT Science Chapter 1.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("science10"), whatYouLearn:["Chemical equation writing","Balancing equations","Combination reactions","Decomposition reactions","Displacement reactions","Oxidation and reduction"], quiz:[] },
  { title:"Class 10 Science — Acids Bases and Salts", description:"Study properties of acids and bases, pH scale, neutralisation and important salts for Class 10 NCERT Chapter 2.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("science10"), whatYouLearn:["Properties of acids and bases","Indicators","Acids and bases in solution","pH scale","Salts and their types","Bleaching powder, baking soda, washing soda"], quiz:[] },
  { title:"Class 10 Science — Metals and Non-Metals", description:"Explore physical and chemical properties, reactivity series, extraction of metals and corrosion for Class 10 Science.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("chem11"), whatYouLearn:["Physical properties of metals","Chemical properties of metals","Reactivity series","Extraction of metals","Corrosion","Alloys"], quiz:[] },
  { title:"Class 10 Science — Carbon and Its Compounds", description:"Understand bonding in carbon, functional groups, homologous series, soaps and detergents for NCERT Class 10.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("chem11"), whatYouLearn:["Covalent bonding in carbon","Versatile nature of carbon","Functional groups","Homologous series","Nomenclature","Soaps and detergents"], quiz:[] },
  { title:"Class 10 Science — Life Processes", description:"Study nutrition, respiration, transportation and excretion in plants and animals for NCERT Class 10 Chapter 6.", instructor:"Biomentors", category:"Science", duration:"3h 00m", ...t("bio11"), whatYouLearn:["What are life processes","Nutrition in plants and animals","Respiration: aerobic and anaerobic","Transportation in plants","Transportation in animals","Excretion"], quiz:[] },
  { title:"Class 10 Science — Control and Coordination", description:"Learn about nervous system, reflex action, hormones and their effects in plants and animals for Class 10.", instructor:"Biomentors", category:"Science", duration:"2h 30m", ...t("bio11"), whatYouLearn:["Nervous system overview","Neurons","Reflex action","Human brain","Coordination in plants","Hormones in animals"], quiz:[] },
  { title:"Class 10 Science — Electricity", description:"Understand electric charge, current, resistance, Ohm's law, series-parallel circuits and power for Class 10 Science.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Electric charge and current","Potential difference","Resistance and Ohm's law","Series and parallel circuits","Heating effects","Electric power"], quiz:[] },
  { title:"Class 10 Science — Magnetic Effects of Current", description:"Study magnetic field, solenoid, force on current-carrying conductor, motors and electromagnetic induction for Class 10.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("physics11"), whatYouLearn:["Magnetic field and field lines","Magnetic field due to current","Solenoid and electromagnet","Force on current-carrying conductor","Electric motor","Electromagnetic induction"], quiz:[] },
  { title:"Class 10 Science — Light Reflection and Refraction", description:"Learn reflection in mirrors, refraction in lenses, mirror formula, lens formula and magnification for Class 10 Science.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Laws of reflection","Spherical mirrors","Mirror formula and magnification","Refraction of light","Lenses","Lens formula and power"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // CLASS 11 — CHAPTER-WISE PHYSICS, CHEMISTRY, MATHS
  // ════════════════════════════════════════════════════════════════
  { title:"Class 11 Physics — Units and Measurements", description:"Study physical quantities, units, dimensions, measurement errors and significant figures for Class 11 NCERT Physics.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("physics11"), whatYouLearn:["Physical quantities and units","SI system","Dimensions of physical quantities","Dimensional analysis","Errors in measurement","Significant figures"], quiz:[] },
  { title:"Class 11 Physics — Motion in a Straight Line", description:"Study kinematics in one dimension — displacement, velocity, acceleration and equations of motion for Class 11.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Position and path length","Displacement and velocity","Acceleration","Kinematic equations","Graphs of motion","Relative velocity"], quiz:[] },
  { title:"Class 11 Physics — Motion in a Plane", description:"Learn vectors, projectile motion and circular motion for Class 11 NCERT Physics Chapter 4.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Scalars and vectors","Addition of vectors","Projectile motion","Horizontal projectile","Uniform circular motion","Centripetal acceleration"], quiz:[] },
  { title:"Class 11 Physics — Laws of Motion", description:"Study Newton's three laws, friction, circular motion dynamics and practical applications for Class 11 NCERT.", instructor:"Physics Wallah", category:"Science", duration:"3h 30m", ...t("physics11"), whatYouLearn:["Newton's first law","Newton's second law","Newton's third law","Conservation of momentum","Friction","Circular motion dynamics"], quiz:[] },
  { title:"Class 11 Physics — Work Energy and Power", description:"Understand work done by a force, kinetic energy, potential energy, conservation of energy and power for Class 11.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics11"), whatYouLearn:["Work done","Kinetic energy","Work-energy theorem","Potential energy","Conservation of mechanical energy","Power and collisions"], quiz:[] },
  { title:"Class 11 Chemistry — Some Basic Concepts", description:"Learn mole concept, stoichiometry, atomic mass, empirical formula and limiting reagent for Class 11 NCERT Chemistry.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("chem11"), whatYouLearn:["Laws of chemical combination","Atomic and molecular mass","Mole concept","Molar mass","Stoichiometry","Limiting reagent"], quiz:[] },
  { title:"Class 11 Chemistry — Structure of Atom", description:"Study Bohr model, quantum numbers, orbitals and electronic configuration for Class 11 NCERT Chemistry Chapter 2.", instructor:"Physics Wallah", category:"Science", duration:"3h 30m", ...t("chem11"), whatYouLearn:["Subatomic particles","Atomic models","Quantum mechanical model","Quantum numbers","Shapes of orbitals","Electronic configuration"], quiz:[] },
  { title:"Class 11 Chemistry — Chemical Bonding", description:"Understand ionic and covalent bonding, VSEPR theory, hybridisation, molecular orbital theory for Class 11.", instructor:"Physics Wallah", category:"Science", duration:"4h 00m", ...t("chem11"), whatYouLearn:["Ionic bond formation","Covalent bonding","Lewis structures","VSEPR theory","Hybridisation: sp, sp2, sp3","Molecular orbital theory"], quiz:[] },
  { title:"Class 11 Chemistry — Thermodynamics", description:"Study first and second laws of thermodynamics, enthalpy, entropy, Gibbs energy for Class 11 NCERT Chemistry.", instructor:"Physics Wallah", category:"Science", duration:"3h 30m", ...t("chem11"), whatYouLearn:["System and surroundings","Internal energy and enthalpy","First law of thermodynamics","Hess's law","Entropy","Gibbs energy and spontaneity"], quiz:[] },
  { title:"Class 11 Mathematics — Sets", description:"Learn sets, types of sets, Venn diagrams, operations on sets and practical problems for Class 11 NCERT Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math11"), whatYouLearn:["Sets representation","Types of sets","Subsets","Venn diagrams","Operations: union, intersection","De Morgan's laws"], quiz:[] },
  { title:"Class 11 Mathematics — Trigonometric Functions", description:"Master trigonometric functions, identities, equations and their graphs for Class 11 NCERT Mathematics Chapter 3.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"4h 00m", ...t("math11"), whatYouLearn:["Angles and arc length","Trigonometric functions","Domain and range","Graphs of trig functions","Trig identities","Trigonometric equations"], quiz:[] },
  { title:"Class 11 Mathematics — Permutations and Combinations", description:"Study counting principles, factorial, permutations and combinations with applications for Class 11 Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math11"), whatYouLearn:["Fundamental counting principle","Factorial notation","Permutations","Permutations with repetition","Combinations","Practical applications"], quiz:[] },
  { title:"Class 11 Mathematics — Binomial Theorem", description:"Learn binomial theorem, general and middle terms, and applications for Class 11 NCERT Mathematics Chapter 8.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math11"), whatYouLearn:["Binomial theorem for positive integral index","Pascal's triangle","General term","Middle term","Binomial coefficients","Applications"], quiz:[] },
  { title:"Class 11 Mathematics — Limits and Derivatives", description:"Introduction to limits, algebra of limits, standard limits and derivatives for Class 11 NCERT Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 30m", ...t("calculus"), whatYouLearn:["Intuitive idea of limits","Limits of polynomials","Standard limits","Differentiation","Algebra of derivatives","Derivatives of trigonometric functions"], quiz:[] },
  { title:"Class 11 Biology — Cell: Structure and Function", description:"Detailed study of prokaryotic and eukaryotic cells, cell organelles and their functions for Class 11 NCERT Biology.", instructor:"Biomentors", category:"Science", duration:"3h 00m", ...t("bio11"), whatYouLearn:["Cell theory","Prokaryotic cell","Eukaryotic cell","Cell membrane","Cell wall","Organelles: mitochondria, chloroplast, ER, Golgi"], quiz:[] },
  { title:"Class 11 Biology — Biomolecules", description:"Study carbohydrates, proteins, lipids, nucleic acids and enzymes for Class 11 NCERT Biology Chapter 9.", instructor:"Biomentors", category:"Science", duration:"2h 30m", ...t("bio11"), whatYouLearn:["How to analyse chemical composition","Amino acids and proteins","Polysaccharides","Nucleic acids — DNA and RNA","Enzymes and their properties","Metabolic basis of living state"], quiz:[] },
  { title:"Class 11 Biology — Plant Kingdom", description:"Classification of plants — algae, bryophytes, pteridophytes, gymnosperms and angiosperms for Class 11 NCERT.", instructor:"Biomentors", category:"Science", duration:"2h 30m", ...t("bio11"), whatYouLearn:["Algae and their types","Bryophytes","Pteridophytes","Gymnosperms","Angiosperms","Plant life cycles"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // CLASS 12 — CHAPTER-WISE
  // ════════════════════════════════════════════════════════════════
  { title:"Class 12 Mathematics — Relations and Functions", description:"Study types of relations and functions, composition, invertible functions for Class 12 NCERT Mathematics Chapter 1.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math12"), whatYouLearn:["Types of relations","Types of functions","Composition of functions","Invertible functions","Binary operations","Practical problems"], quiz:[] },
  { title:"Class 12 Mathematics — Inverse Trigonometry", description:"Learn inverse trigonometric functions, principal values, properties and simplifications for Class 12 NCERT.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"2h 30m", ...t("math12"), whatYouLearn:["Inverse trigonometric functions","Principal value branch","Properties","Simplifying expressions","Equations involving inverse trig","Applications"], quiz:[] },
  { title:"Class 12 Mathematics — Matrices", description:"Master matrix operations, types, transpose, symmetric, skew-symmetric and elementary row operations for Class 12.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math12"), whatYouLearn:["Types of matrices","Operations on matrices","Transpose of a matrix","Symmetric and skew-symmetric matrices","Elementary operations","Invertible matrices"], quiz:[] },
  { title:"Class 12 Mathematics — Determinants", description:"Study determinants, properties, cofactors, adjoint, inverse and applications for Class 12 NCERT Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("math12"), whatYouLearn:["Determinant expansion","Properties of determinants","Area of triangle","Minors and cofactors","Adjoint and inverse","Applications in system of equations"], quiz:[] },
  { title:"Class 12 Mathematics — Continuity and Differentiability", description:"Learn continuity, differentiability, chain rule, implicit and logarithmic differentiation for Class 12.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"4h 00m", ...t("calculus"), whatYouLearn:["Continuity of functions","Differentiability","Chain rule","Implicit differentiation","Logarithmic differentiation","Mean value theorem"], quiz:[] },
  { title:"Class 12 Mathematics — Applications of Derivatives", description:"Study rate of change, increasing/decreasing functions, maxima, minima and tangents for Class 12 NCERT.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 30m", ...t("calculus"), whatYouLearn:["Rate of change","Increasing and decreasing functions","Tangents and normals","Approximations","Maxima and minima","Point of inflection"], quiz:[] },
  { title:"Class 12 Mathematics — Integrals", description:"Master integration techniques — substitution, partial fractions, by parts and definite integrals for Class 12.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"5h 00m", ...t("calculus"), whatYouLearn:["Integration as reverse differentiation","Methods of integration","Integration by substitution","Integration by partial fractions","Integration by parts","Definite integrals"], quiz:[] },
  { title:"Class 12 Mathematics — Differential Equations", description:"Learn formation, order, degree and solutions of differential equations for Class 12 NCERT Mathematics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"3h 00m", ...t("calculus"), whatYouLearn:["Order and degree","General and particular solutions","Variable separable method","Homogeneous equations","Linear differential equations","Applications"], quiz:[] },
  { title:"Class 12 Physics — Electrostatics", description:"Study electric charges, Coulomb's law, electric field, potential, capacitors for Class 12 NCERT Physics Chapter 1.", instructor:"Physics Wallah", category:"Science", duration:"4h 00m", ...t("physics12"), whatYouLearn:["Electric charges and Coulomb's law","Electric field","Electric field lines","Electric potential","Equipotential surfaces","Capacitors and capacitance"], quiz:[] },
  { title:"Class 12 Physics — Current Electricity", description:"Learn drift velocity, Ohm's law, resistivity, Kirchhoff's laws, Wheatstone bridge for Class 12 NCERT Physics.", instructor:"Physics Wallah", category:"Science", duration:"4h 00m", ...t("physics12"), whatYouLearn:["Electric current and drift velocity","Ohm's law and resistance","Resistivity and conductivity","Kirchhoff's laws","Wheatstone bridge","Meter bridge and potentiometer"], quiz:[] },
  { title:"Class 12 Physics — Magnetism and Matter", description:"Study bar magnet, magnetic field lines, earth's magnetism, diamagnetic and paramagnetic substances for Class 12.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("physics12"), whatYouLearn:["Bar magnet and dipole","Magnetic field lines","Torque on bar magnet","The Earth's magnetism","Magnetic properties of materials","Permanent magnets"], quiz:[] },
  { title:"Class 12 Physics — Electromagnetic Induction", description:"Learn Faraday's laws, Lenz's law, self and mutual inductance and eddy currents for Class 12 NCERT Physics.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("physics12"), whatYouLearn:["Faraday's law of induction","Lenz's law","Motional EMF","Eddy currents","Inductance: self and mutual","AC generator"], quiz:[] },
  { title:"Class 12 Chemistry — Solid State", description:"Study crystal structure, unit cells, defects and electrical and magnetic properties of solids for Class 12 NCERT.", instructor:"Physics Wallah", category:"Science", duration:"2h 30m", ...t("chem12"), whatYouLearn:["Amorphous and crystalline solids","Crystal lattice and unit cell","Number of atoms in unit cell","Close packing","Imperfections in solids","Electrical and magnetic properties"], quiz:[] },
  { title:"Class 12 Chemistry — Solutions", description:"Understand types of solutions, concentration, colligative properties, osmosis and van't Hoff factor for Class 12.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("chem12"), whatYouLearn:["Types of solutions","Concentration terms","Vapour pressure","Raoult's law","Colligative properties","Van't Hoff factor"], quiz:[] },
  { title:"Class 12 Chemistry — Electrochemistry", description:"Study electrochemical cells, Nernst equation, conductance, electrolysis and batteries for Class 12 NCERT.", instructor:"Physics Wallah", category:"Science", duration:"3h 00m", ...t("chem12"), whatYouLearn:["Electrochemical cells","Galvanic cells","Nernst equation","Gibbs energy","Conductance of solutions","Electrolytic cells and batteries"], quiz:[] },
  { title:"Class 12 Biology — Reproduction in Organisms", description:"Study asexual and sexual reproduction in plants and animals for Class 12 NCERT Biology Chapter 1.", instructor:"Biomentors", category:"Science", duration:"2h 00m", ...t("bio12"), whatYouLearn:["Life span and reproduction","Asexual reproduction modes","Sexual reproduction","Pre-fertilisation events","Fertilisation","Post-fertilisation events"], quiz:[] },
  { title:"Class 12 Biology — Genetics and Heredity", description:"Learn Mendelian genetics, law of segregation, law of independent assortment and chromosomal theory for Class 12.", instructor:"Biomentors", category:"Science", duration:"3h 30m", ...t("bio12"), whatYouLearn:["Mendel's experiments","Law of segregation","Law of independent assortment","Chromosomal theory of inheritance","Sex determination","Mutation"], quiz:[] },
  { title:"Class 12 Biology — Molecular Basis of Inheritance", description:"Study DNA structure, replication, transcription, translation and regulation of gene expression for Class 12 Biology.", instructor:"Biomentors", category:"Science", duration:"4h 00m", ...t("bio12"), whatYouLearn:["DNA structure (Watson and Crick)","Packaging of DNA","DNA replication","Transcription","Genetic code","Translation and regulation"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // JEE / NEET — TOPIC-WISE
  // ════════════════════════════════════════════════════════════════
  { title:"JEE — Coordinate Geometry Complete", description:"Complete coordinate geometry for JEE Mains and Advanced — straight lines, circles, parabola, ellipse and hyperbola.", instructor:"IIT Alumni Faculty", category:"Mathematics", duration:"15h 00m", ...t("jee"), whatYouLearn:["Straight lines — all forms","Circle: standard and general","Parabola and its properties","Ellipse standard form","Hyperbola","Previous year problems"], quiz:[] },
  { title:"JEE — Calculus: Limits Derivatives Integration", description:"Complete calculus for JEE — limits, continuity, differentiation, applications, indefinite and definite integration.", instructor:"IIT Alumni Faculty", category:"Mathematics", duration:"20h 00m", ...t("calculus"), whatYouLearn:["Limits and L'Hopital's rule","Continuity and differentiability","Applications of derivatives","Indefinite integration techniques","Definite integration and properties","Area under curves"], quiz:[] },
  { title:"JEE Physics — Electrostatics and Current Electricity", description:"In-depth coverage of electrostatics and current electricity with 500+ numerical problems for JEE Mains and Advanced.", instructor:"IIT Alumni Faculty", category:"Science", duration:"18h 00m", ...t("physics12"), whatYouLearn:["Coulomb's law and electric field","Gauss's law applications","Electric potential and potential energy","Capacitors and energy","Ohm's law and circuits","Kirchhoff's laws and bridges"], quiz:[] },
  { title:"JEE Physics — Optics Complete", description:"Ray optics and wave optics for JEE — mirrors, lenses, interference, diffraction and polarisation with numericals.", instructor:"IIT Alumni Faculty", category:"Science", duration:"12h 00m", ...t("physics12"), whatYouLearn:["Reflection and refraction","Mirrors and lenses","Optical instruments","Wave optics and interference","Young's double slit","Diffraction and polarisation"], quiz:[] },
  { title:"JEE Chemistry — Organic Reaction Mechanisms", description:"Complete organic chemistry reaction mechanisms for JEE — substitution, elimination, addition and rearrangements.", instructor:"IIT Alumni Faculty", category:"Science", duration:"16h 00m", ...t("chem12"), whatYouLearn:["Reaction intermediates","Substitution: SN1 and SN2","Elimination: E1 and E2","Addition to carbonyl","Aldol and Claisen condensation","Rearrangements"], quiz:[] },
  { title:"NEET — Human Physiology Complete", description:"Complete human physiology for NEET — digestion, respiration, circulation, excretion, nervous and endocrine systems.", instructor:"NEET Expert Faculty", category:"Science", duration:"20h 00m", ...t("neet"), whatYouLearn:["Digestion and absorption","Breathing and gas exchange","Body fluids and circulation","Excretory products and elimination","Locomotion and movement","Neural control and endocrine system"], quiz:[] },
  { title:"NEET — Genetics and Evolution Complete", description:"Genetics and evolution for NEET — inheritance, DNA, molecular biology, origin of life and evolutionary evidence.", instructor:"NEET Expert Faculty", category:"Science", duration:"16h 00m", ...t("neet"), whatYouLearn:["Principles of inheritance","Chromosomal basis of inheritance","Molecular basis of inheritance","DNA fingerprinting","Origin of life","Evidences of evolution"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // PROFESSIONAL — PROGRAMMING
  // ════════════════════════════════════════════════════════════════
  { title:"Python Basics — Complete Beginner Course", description:"Learn Python from absolute scratch — syntax, variables, loops, functions, lists and file handling with projects.", instructor:"freeCodeCamp", category:"Programming", duration:"6h 00m", ...t("python"), whatYouLearn:["Variables and data types","Control flow: if-else","Loops: for and while","Functions and modules","Lists, tuples, dictionaries","File handling and exceptions"], quiz:[] },
  { title:"Python Intermediate — OOP and Modules", description:"Object-oriented programming in Python — classes, inheritance, polymorphism, decorators and popular libraries.", instructor:"Corey Schafer", category:"Programming", duration:"8h 00m", ...t("python"), whatYouLearn:["Classes and objects","Inheritance and polymorphism","Magic methods","Decorators","Generators and iterators","Popular libraries: os, sys, json"], quiz:[] },
  { title:"Python Advanced — Projects and APIs", description:"Build real Python projects — web scraping, REST APIs with Flask, automation scripts and data processing.", instructor:"Tech With Tim", category:"Programming", duration:"10h 00m", ...t("python"), whatYouLearn:["Web scraping with BeautifulSoup","REST API with Flask","Working with JSON APIs","Automation with Selenium","Data processing pipelines","Deploying Python apps"], quiz:[] },
  { title:"JavaScript Complete Guide 2024", description:"Complete modern JavaScript — ES6+, DOM manipulation, async programming, fetch API and module system.", instructor:"Traversy Media", category:"Programming", duration:"7h 00m", ...t("js"), whatYouLearn:["Variables, functions and scope","ES6+ features (arrow, destructuring)","DOM manipulation","Events and event delegation","Promises and async/await","Fetch API and modules"], quiz:[] },
  { title:"TypeScript for JavaScript Developers", description:"Learn TypeScript from scratch — types, interfaces, generics, classes and integration with React and Node.js.", instructor:"Academind", category:"Programming", duration:"5h 00m", ...t("js"), whatYouLearn:["TypeScript basics and types","Interfaces and type aliases","Classes and access modifiers","Generics","Decorators","TypeScript with React and Node"], quiz:[] },
  { title:"Java Complete Course — Beginner to Advanced", description:"Complete Java programming — OOP, collections, streams, multithreading, JDBC and Spring Boot introduction.", instructor:"Telusko", category:"Programming", duration:"12h 00m", ...t("java"), whatYouLearn:["Java syntax and OOP","Collections framework","Streams and lambda expressions","Multithreading and concurrency","JDBC and databases","Spring Boot introduction"], quiz:[] },
  { title:"C++ Complete Course", description:"Learn C++ from basics to advanced — pointers, memory management, STL, templates and competitive programming.", instructor:"CodeWithHarry", category:"Programming", duration:"10h 00m", ...t("cpp"), whatYouLearn:["C++ syntax and basics","Pointers and references","OOP in C++","STL: vector, map, set","Templates","Competitive programming techniques"], quiz:[] },
  { title:"Data Structures — Complete Course", description:"Master all data structures with implementations — arrays, linked lists, stacks, queues, trees, graphs and heaps.", instructor:"Abdul Bari", category:"Programming", duration:"20h 00m", ...t("python"), whatYouLearn:["Arrays and linked lists","Stacks and queues","Trees and BST","Heaps and priority queues","Hashing","Graphs: BFS, DFS"], quiz:[] },
  { title:"Algorithms — Complete Course", description:"Learn algorithm design techniques — divide and conquer, greedy, dynamic programming, graph algorithms and complexity.", instructor:"Abdul Bari", category:"Programming", duration:"18h 00m", ...t("python"), whatYouLearn:["Algorithm analysis and Big-O","Sorting algorithms","Divide and conquer","Greedy algorithms","Dynamic programming","Graph algorithms"], quiz:[] },
  { title:"SQL and Database Design", description:"Learn SQL from basics to advanced — DDL, DML, joins, subqueries, indexing and database normalisation.", instructor:"freeCodeCamp", category:"Programming", duration:"5h 00m", ...t("sql"), whatYouLearn:["SQL basics: SELECT, INSERT, UPDATE","Joins: inner, left, right, full","Subqueries and CTEs","Aggregate functions","Indexing and optimisation","Database design and normalisation"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // PROFESSIONAL — WEB DEVELOPMENT
  // ════════════════════════════════════════════════════════════════
  { title:"HTML5 and CSS3 — Complete Course", description:"Build modern websites from scratch with HTML5 and CSS3 — layouts, animations, responsive design and Flexbox/Grid.", instructor:"Kevin Powell", category:"Web Development", duration:"5h 00m", ...t("webdev"), whatYouLearn:["HTML5 semantic elements","CSS selectors and specificity","Flexbox layout","CSS Grid","Responsive design and media queries","CSS animations and transitions"], quiz:[] },
  { title:"React.js — Complete 2024 Course", description:"Build professional React apps with hooks, context, React Router, custom hooks and state management.", instructor:"Scrimba", category:"Web Development", duration:"8h 00m", ...t("react"), whatYouLearn:["React fundamentals and JSX","useState and useEffect","React Router v6","Context API and useReducer","Custom hooks","Performance optimisation"], quiz:[] },
  { title:"Next.js — Full Stack React Framework", description:"Build production-ready full stack apps with Next.js — SSR, SSG, API routes, authentication and deployment.", instructor:"Traversy Media", category:"Web Development", duration:"7h 00m", ...t("react"), whatYouLearn:["Pages and routing in Next.js","Server-side rendering","Static generation","API routes","Authentication with NextAuth","Deployment on Vercel"], quiz:[] },
  { title:"Node.js and Express — REST API Development", description:"Build scalable REST APIs with Node.js and Express — middleware, authentication, file uploads and MongoDB.", instructor:"Brad Traversy", category:"Web Development", duration:"6h 00m", ...t("node"), whatYouLearn:["Node.js fundamentals","Express routing and middleware","REST API design","JWT authentication","MongoDB with Mongoose","File uploads and error handling"], quiz:[] },
  { title:"MongoDB — Complete NoSQL Database Course", description:"Learn MongoDB — CRUD operations, aggregation pipeline, indexing, Atlas and integration with Node.js.", instructor:"freeCodeCamp", category:"Web Development", duration:"4h 00m", ...t("node"), whatYouLearn:["MongoDB basics and CRUD","Query operators","Aggregation pipeline","Indexing and performance","MongoDB Atlas","Integration with Express"], quiz:[] },
  { title:"MERN Stack — Full Stack Development", description:"Build complete MERN stack applications — MongoDB, Express, React and Node with authentication and deployment.", instructor:"Traversy Media", category:"Web Development", duration:"12h 00m", ...t("webdev"), whatYouLearn:["Setting up MERN stack","Building REST API","React frontend development","JWT auth in MERN","Redux state management","Deployment on Heroku/Render"], quiz:[] },
  { title:"Vue.js 3 — Complete Guide", description:"Learn Vue.js 3 with Composition API, Vue Router, Pinia state management and building real-world applications.", instructor:"Maximilian Schwarzmüller", category:"Web Development", duration:"6h 00m", ...t("react"), whatYouLearn:["Vue 3 basics and directives","Composition API","Vue Router 4","Pinia state management","Component communication","Building projects"], quiz:[] },
  { title:"Django — Python Web Framework", description:"Build web applications with Django — models, views, templates, REST API with DRF and authentication.", instructor:"Corey Schafer", category:"Web Development", duration:"8h 00m", ...t("python"), whatYouLearn:["Django project structure","Models and database","Views and URLs","Templates and forms","Django REST Framework","Authentication and deployment"], quiz:[] },
  { title:"Docker and Containerisation", description:"Learn Docker from scratch — containers, images, Dockerfile, Docker Compose and deploying containerised applications.", instructor:"TechWorld with Nana", category:"Web Development", duration:"5h 00m", ...t("devops"), whatYouLearn:["What is Docker?","Docker images and containers","Dockerfile","Docker Compose","Networking in Docker","Deploying with Docker"], quiz:[] },
  { title:"AWS Cloud Practitioner — Complete Guide", description:"Master AWS fundamentals — EC2, S3, RDS, Lambda, IAM, VPC and prepare for the AWS Cloud Practitioner exam.", instructor:"freeCodeCamp", category:"Web Development", duration:"10h 00m", ...t("cloud"), whatYouLearn:["AWS global infrastructure","IAM users and policies","EC2 and ELB","S3 and storage services","RDS and DynamoDB","Lambda and serverless"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // PROFESSIONAL — DATA SCIENCE & AI
  // ════════════════════════════════════════════════════════════════
  { title:"Data Science with Python — Complete Course", description:"End-to-end data science with Python — NumPy, Pandas, visualization, ML models and deploying solutions.", instructor:"Keith Galli", category:"Data Science", duration:"8h 00m", ...t("ds"), whatYouLearn:["NumPy arrays and operations","Pandas DataFrames","Data visualization: Matplotlib, Seaborn","Statistical analysis","Machine learning with scikit-learn","Model deployment"], quiz:[] },
  { title:"Machine Learning — Andrew Ng Style", description:"Complete machine learning with mathematical foundations — regression, classification, clustering, neural networks.", instructor:"Andrej Karpathy", category:"Data Science", duration:"15h 00m", ...t("ml"), whatYouLearn:["Supervised learning","Linear and logistic regression","Support vector machines","Decision trees and random forests","Unsupervised learning","Model evaluation metrics"], quiz:[] },
  { title:"Deep Learning — Neural Networks from Scratch", description:"Build neural networks from scratch, then with PyTorch — CNNs, RNNs, transformers and real-world applications.", instructor:"Andrej Karpathy", category:"Data Science", duration:"18h 00m", ...t("dl"), whatYouLearn:["Neural network mathematics","Backpropagation","CNNs for image classification","RNNs and LSTMs","Attention mechanism and transformers","Fine-tuning pretrained models"], quiz:[] },
  { title:"Natural Language Processing with Python", description:"Learn NLP from basics to BERT — text preprocessing, sentiment analysis, named entity recognition and transformers.", instructor:"Hugging Face", category:"Data Science", duration:"10h 00m", ...t("ml"), whatYouLearn:["Text preprocessing and tokenization","Bag of words and TF-IDF","Sentiment analysis","Named entity recognition","Word embeddings","BERT and fine-tuning"], quiz:[] },
  { title:"Power BI — Data Visualization Masterclass", description:"Master Microsoft Power BI — connecting data sources, DAX formulas, creating reports and dashboards.", instructor:"Guy in a Cube", category:"Data Science", duration:"6h 00m", ...t("ds"), whatYouLearn:["Power BI interface","Importing data sources","Data modeling","DAX formulas","Creating visualizations","Publishing reports"], quiz:[] },
  { title:"Tableau — Data Analytics and Visualization", description:"Learn Tableau from scratch — charts, calculations, dashboards, storytelling with data and Tableau Public.", instructor:"Simplilearn", category:"Data Science", duration:"5h 00m", ...t("ds"), whatYouLearn:["Tableau interface","Connecting to data","Basic charts","Calculated fields","Dashboards and stories","Publishing to Tableau Public"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // PROFESSIONAL — BUSINESS & DESIGN
  // ════════════════════════════════════════════════════════════════
  { title:"Digital Marketing — Complete Course 2024", description:"Master digital marketing — SEO, social media, Google Ads, email marketing, content strategy and analytics.", instructor:"Neil Patel", category:"Business", duration:"8h 00m", ...t("marketing"), whatYouLearn:["SEO: on-page and off-page","Social media marketing","Google Ads and PPC","Email marketing","Content marketing","Google Analytics 4"], quiz:[] },
  { title:"SEO Masterclass — Rank on Google", description:"Learn search engine optimisation — keyword research, on-page SEO, link building, technical SEO and local SEO.", instructor:"Backlinko", category:"Business", duration:"5h 00m", ...t("marketing"), whatYouLearn:["Keyword research techniques","On-page optimisation","Technical SEO","Link building strategies","Local SEO","SEO audit"], quiz:[] },
  { title:"Product Management — Zero to PM", description:"Complete product management course — product thinking, user research, roadmapping, metrics and stakeholder management.", instructor:"Shreyas Doshi", category:"Business", duration:"6h 00m", ...t("general"), whatYouLearn:["Product thinking and strategy","User research and personas","Writing PRDs","Product roadmapping","Metrics and KPIs","Stakeholder management"], quiz:[] },
  { title:"Figma — UI Design Complete Course", description:"Master Figma for UI/UX design — components, auto-layout, prototyping, design systems and developer handoff.", instructor:"DesignCode", category:"Design", duration:"6h 00m", ...t("figma"), whatYouLearn:["Figma interface and basics","Frames, groups and layers","Components and variants","Auto-layout","Prototyping and interactions","Design systems"], quiz:[] },
  { title:"Graphic Design Fundamentals", description:"Learn graphic design principles — typography, colour theory, composition, branding and Adobe Illustrator basics.", instructor:"Canva Design School", category:"Design", duration:"4h 00m", ...t("design"), whatYouLearn:["Design principles","Typography fundamentals","Colour theory","Composition and layout","Branding basics","Adobe Illustrator essentials"], quiz:[] },
  { title:"Financial Literacy — Personal Finance", description:"Master personal finance — budgeting, investing, mutual funds, SIP, insurance, tax planning and retirement.", instructor:"CA Rachna Ranade", category:"Business", duration:"4h 00m", ...t("accounts"), whatYouLearn:["Budgeting and saving","Emergency fund","Mutual funds and SIP","Stock market basics","Insurance planning","Tax planning in India"], quiz:[] },

  // ════════════════════════════════════════════════════════════════
  // GENERAL / COMPETITIVE EXAMS
  // ════════════════════════════════════════════════════════════════
  { title:"UPSC CSE — Prelims Complete Strategy", description:"Complete UPSC Civil Services Prelims preparation — GS Paper 1, CSAT, current affairs, books and resources.", instructor:"Vision IAS", category:"General", duration:"20h 00m", ...t("general"), whatYouLearn:["UPSC exam pattern and syllabus","History and polity for prelims","Geography preparation","Economy and environment","Science and technology","CSAT preparation"], quiz:[] },
  { title:"Indian Polity — Complete Course (UPSC/SSC)", description:"Complete Indian Polity for competitive exams — Constitution, fundamental rights, Parliament, judiciary and federalism.", instructor:"Laxmikanth Summary", category:"General", duration:"12h 00m", ...t("polsci"), whatYouLearn:["Making of the Constitution","Fundamental rights and DPSP","Parliament and state legislature","President and Prime Minister","Judiciary and courts","Local government and federalism"], quiz:[] },
  { title:"Indian History — Ancient, Medieval and Modern", description:"Complete Indian History for UPSC, SSC, bank and other competitive exams with maps and timeline.", instructor:"History Optional Faculty", category:"History", duration:"18h 00m", ...t("history"), whatYouLearn:["Prehistoric and Indus Valley civilisation","Vedic age and kingdoms","Mauryas and Guptas","Medieval India: Sultans and Mughals","Colonial period and freedom struggle","Modern India post-independence"], quiz:[] },
  { title:"General Science for Competitive Exams", description:"Physics, Chemistry and Biology for SSC, RRB, UPSC and other competitive exams with MCQs and tricks.", instructor:"Expert Faculty", category:"Science", duration:"8h 00m", ...t("science9"), whatYouLearn:["Physics: forces, light, sound, electricity","Chemistry: periodic table, acids, bases","Biology: cell, nutrition, diseases","Science and technology current affairs","MCQ practice","Memory tricks"], quiz:[] },
  { title:"Quantitative Aptitude — Banking and SSC", description:"Complete quantitative aptitude for bank PO, clerk, SSC CGL, CHSL — arithmetic, algebra, geometry and data interpretation.", instructor:"Adda247", category:"Mathematics", duration:"15h 00m", ...t("stats"), whatYouLearn:["Number system and HCF/LCM","Percentage and profit-loss","Simple and compound interest","Time, work and speed","Data interpretation","Geometry and mensuration"], quiz:[] },
  { title:"English for Competitive Exams", description:"Grammar, reading comprehension, vocabulary, sentence correction and verbal ability for bank, SSC and UPSC exams.", instructor:"Wren and Martin", category:"Language", duration:"8h 00m", ...t("english"), whatYouLearn:["Grammar: parts of speech and tenses","Reading comprehension techniques","Vocabulary: root words and synonyms","Sentence correction","Para-jumbles","Verbal ability tricks"], quiz:[] },
];

// ── Main seeder function ─────────────────────────────────────────
async function seed() {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected!\n");
    console.log(`📚 Total courses to process: ${ALL_COURSES.length}\n`);

    let inserted = 0, skipped = 0, failed = 0;

    for (let i = 0; i < ALL_COURSES.length; i++) {
      const course = ALL_COURSES[i];
      try {
        const exists = await Course.findOne({ title: course.title });
        if (exists) {
          process.stdout.write(`  ⏭  Skipped: ${course.title.slice(0, 50)}\n`);
          skipped++;
        } else {
          await Course.create(course);
          process.stdout.write(`  ✅ [${inserted + 1}] Added: ${course.title.slice(0, 55)}\n`);
          inserted++;
        }
      } catch (err) {
        process.stdout.write(`  ❌ Failed: ${course.title.slice(0, 40)} — ${err.message}\n`);
        failed++;
      }
    }

    const total = await Course.countDocuments();
    console.log(`\n${"═".repeat(65)}`);
    console.log(`🎉 Seeding complete!`);
    console.log(`   ✅ Inserted : ${inserted} new courses`);
    console.log(`   ⏭  Skipped  : ${skipped} (already exist)`);
    console.log(`   ❌ Failed   : ${failed}`);
    console.log(`   📚 Total    : ${total} courses in your database`);
    console.log(`${"═".repeat(65)}\n`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Fatal error:", err.message);
    process.exit(1);
  }
}

seed();