// ================================================================
// SCHOOL COURSES SEEDER — Class 7 to 12 with correct thumbnails
// Usage: node seedSchoolCourses.js
// Place in: backend/seedSchoolCourses.js
// ================================================================

require("dotenv").config();
const mongoose = require("mongoose");
const Course = require("./models/Course");

const MONGO_URI = process.env.MONGO_URI || process.env.MONGODB_URI || process.env.DB_URI;

// ── Subject-matched YouTube video IDs ────────────────────────────
// These are real educational YouTube videos matching the subject
const T = {
  math:     { v: "NybHckSEQBI", thumb: "https://img.youtube.com/vi/NybHckSEQBI/maxresdefault.jpg", url: "https://www.youtube.com/embed/NybHckSEQBI" },
  science:  { v: "URUJD5NEXC8", thumb: "https://img.youtube.com/vi/URUJD5NEXC8/maxresdefault.jpg", url: "https://www.youtube.com/embed/URUJD5NEXC8" },
  physics:  { v: "b1t41Q3xRM8", thumb: "https://img.youtube.com/vi/b1t41Q3xRM8/maxresdefault.jpg", url: "https://www.youtube.com/embed/b1t41Q3xRM8" },
  chemistry:{ v: "bka20Q9TN6M", thumb: "https://img.youtube.com/vi/bka20Q9TN6M/maxresdefault.jpg", url: "https://www.youtube.com/embed/bka20Q9TN6M" },
  biology:  { v: "URUJD5NEXC8", thumb: "https://img.youtube.com/vi/URUJD5NEXC8/maxresdefault.jpg", url: "https://www.youtube.com/embed/URUJD5NEXC8" },
  english:  { v: "0G3_kG5FFfQ", thumb: "https://img.youtube.com/vi/0G3_kG5FFfQ/maxresdefault.jpg", url: "https://www.youtube.com/embed/0G3_kG5FFfQ" },
  hindi:    { v: "2Sj6EMtHYkc", thumb: "https://img.youtube.com/vi/2Sj6EMtHYkc/maxresdefault.jpg", url: "https://www.youtube.com/embed/2Sj6EMtHYkc" },
  sst:      { v: "wOclF9eP5OM", thumb: "https://img.youtube.com/vi/wOclF9eP5OM/maxresdefault.jpg", url: "https://www.youtube.com/embed/wOclF9eP5OM" },
  history:  { v: "Yocja_N5s1I", thumb: "https://img.youtube.com/vi/Yocja_N5s1I/maxresdefault.jpg", url: "https://www.youtube.com/embed/Yocja_N5s1I" },
  cs:       { v: "kqtD5dpn9C8", thumb: "https://img.youtube.com/vi/kqtD5dpn9C8/maxresdefault.jpg", url: "https://www.youtube.com/embed/kqtD5dpn9C8" },
  accounts: { v: "vmEHCJofslg", thumb: "https://img.youtube.com/vi/vmEHCJofslg/maxresdefault.jpg", url: "https://www.youtube.com/embed/vmEHCJofslg" },
  business: { v: "ua-CiDNNj30", thumb: "https://img.youtube.com/vi/ua-CiDNNj30/maxresdefault.jpg", url: "https://www.youtube.com/embed/ua-CiDNNj30" },
  economics:{ v: "xxpc-HPKN28", thumb: "https://img.youtube.com/vi/xxpc-HPKN28/maxresdefault.jpg", url: "https://www.youtube.com/embed/xxpc-HPKN28" },
  calculus: { v: "WUvTyaaNkzM", thumb: "https://img.youtube.com/vi/WUvTyaaNkzM/maxresdefault.jpg", url: "https://www.youtube.com/embed/WUvTyaaNkzM" },
  jee:      { v: "tPYj3fFJGjk", thumb: "https://img.youtube.com/vi/tPYj3fFJGjk/maxresdefault.jpg", url: "https://www.youtube.com/embed/tPYj3fFJGjk" },
  neet:     { v: "GwIo3gDZCVQ", thumb: "https://img.youtube.com/vi/GwIo3gDZCVQ/maxresdefault.jpg", url: "https://www.youtube.com/embed/GwIo3gDZCVQ" },
  geo:      { v: "PUB0TaZ7bhA", thumb: "https://img.youtube.com/vi/PUB0TaZ7bhA/maxresdefault.jpg", url: "https://www.youtube.com/embed/PUB0TaZ7bhA" },
  polsci:   { v: "nu_pCVPKzTk", thumb: "https://img.youtube.com/vi/nu_pCVPKzTk/maxresdefault.jpg", url: "https://www.youtube.com/embed/nu_pCVPKzTk" },
  general:  { v: "W6NZfCO5SIk", thumb: "https://img.youtube.com/vi/W6NZfCO5SIk/maxresdefault.jpg", url: "https://www.youtube.com/embed/W6NZfCO5SIk" },
};

const SCHOOL_COURSES = [

  // ══════════════════════════════════════════════════════════
  // CLASS 7
  // ══════════════════════════════════════════════════════════
  { title:"Class 7 Mathematics (NCERT)", description:"Complete Class 7 Mathematics covering all NCERT chapters — integers, fractions, decimals, algebraic expressions, triangles, and data handling. Explained with solved examples and practice questions.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"18h 00m", videoUrl:T.math.url, thumbnail:T.math.thumb, whatYouLearn:["Integers and rational numbers","Fractions and decimals","Simple equations","Lines and angles","Triangles and their properties","Data handling and probability"], quiz:[] },
  { title:"Class 7 Science (NCERT)", description:"Complete Class 7 Science covering nutrition in plants and animals, heat, acids and bases, physical and chemical changes, weather, soil, and motion and time as per NCERT syllabus.", instructor:"NCERT Expert Faculty", category:"Science", duration:"16h 00m", videoUrl:T.science.url, thumbnail:T.science.thumb, whatYouLearn:["Nutrition in plants and animals","Heat and temperature","Acids, bases and salts","Physical and chemical changes","Weather, climate and adaptation","Motion and time"], quiz:[] },
  { title:"Class 7 English (NCERT - Honeycomb)", description:"Complete Class 7 English covering all chapters from Honeycomb and An Alien Hand. Includes reading comprehension, grammar, writing skills, and vocabulary exercises.", instructor:"NCERT Expert Faculty", category:"Language", duration:"12h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["Reading comprehension skills","Grammar: tenses and voices","Letter and paragraph writing","Vocabulary building","Poetry appreciation","Story analysis"], quiz:[] },
  { title:"Class 7 Hindi (NCERT - Vasant)", description:"Class 7 Hindi covering all chapters from Vasant Part 2 and Durva. Grammar topics include sandhi, samas, and essay writing as per NCERT curriculum.", instructor:"NCERT Expert Faculty", category:"Language", duration:"12h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Vasant chapters and summaries","Grammar: sandhi and samas","Essay and letter writing","Comprehension passages","Poetry recitation and meaning","Vocabulary enrichment"], quiz:[] },
  { title:"Class 7 Social Science (NCERT)", description:"Class 7 Social Science covering History (Our Pasts II), Geography (Our Environment), and Civics (Social and Political Life II) as per NCERT syllabus.", instructor:"NCERT Expert Faculty", category:"History", duration:"14h 00m", videoUrl:T.sst.url, thumbnail:T.sst.thumb, whatYouLearn:["Medieval India and rulers","New kings and kingdoms","Environment and its types","Inside our earth","Democratic government","Markets around us"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // CLASS 8
  // ══════════════════════════════════════════════════════════
  { title:"Class 8 Mathematics (NCERT)", description:"Complete Class 8 Mathematics covering rational numbers, linear equations, quadrilaterals, practical geometry, mensuration, exponents, factorisation, graphs, and playing with numbers.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"20h 00m", videoUrl:T.math.url, thumbnail:T.math.thumb, whatYouLearn:["Rational numbers","Linear equations in one variable","Understanding quadrilaterals","Mensuration (area and volume)","Exponents and powers","Factorisation of algebraic expressions"], quiz:[] },
  { title:"Class 8 Science (NCERT)", description:"Complete Class 8 Science covering crop production, microorganisms, materials (metals, non-metals), combustion, conservation of plants and animals, cell, reproduction, and force.", instructor:"NCERT Expert Faculty", category:"Science", duration:"18h 00m", videoUrl:T.science.url, thumbnail:T.science.thumb, whatYouLearn:["Crop production and management","Microorganisms: friend and foe","Metals and non-metals","Combustion and flame","Cell — structure and function","Force and pressure"], quiz:[] },
  { title:"Class 8 English (NCERT - Honeydew)", description:"Complete Class 8 English based on Honeydew and It So Happened. Covers all prose and poetry chapters with grammar exercises, writing tasks, and comprehension practice.", instructor:"NCERT Expert Faculty", category:"Language", duration:"12h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["Prose chapters from Honeydew","Supplementary reader stories","Grammar: adjectives, adverbs, phrases","Formal and informal writing","Poetry interpretation","Comprehension and vocabulary"], quiz:[] },
  { title:"Class 8 Hindi (NCERT - Vasant)", description:"Class 8 Hindi based on Vasant Part 3. Covers all chapters, grammar topics including kaal, vachya, and alankar, plus essay and story writing.", instructor:"NCERT Expert Faculty", category:"Language", duration:"12h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Vasant Part 3 chapters","Grammar: kaal and vachya","Alankar and chhand","Essay writing skills","Unseen passages","Letter writing"], quiz:[] },
  { title:"Class 8 Social Science (NCERT)", description:"Class 8 Social Science covering History (Our Pasts III), Geography (Resources and Development), and Civics (Social and Political Life III).", instructor:"NCERT Expert Faculty", category:"History", duration:"16h 00m", videoUrl:T.sst.url, thumbnail:T.sst.thumb, whatYouLearn:["British rule in India","Tribals, dikus and the vision of a golden age","Resources: types and conservation","Industries and agriculture","The Indian Constitution","Understanding laws and parliament"], quiz:[] },
  { title:"Class 8 Mathematics — Algebraic Expressions", description:"Learn algebraic expressions, identities, factorisation, and their applications from Class 8 NCERT Mathematics.", instructor:"Magnet Brains", category:"Mathematics", duration:"4h 00m", videoUrl:"https://www.youtube.com/embed/NybHckSEQBI", thumbnail:"https://img.youtube.com/vi/NybHckSEQBI/maxresdefault.jpg", whatYouLearn:["Algebraic expressions","Like and unlike terms","Multiplication of expressions","Identities","Factorisation","Applications"], quiz:[] },
  { title:"Class 8 Science — Microorganisms", description:"Understand microorganisms — bacteria, viruses, fungi, and protozoa — their roles and effects on human health and agriculture.", instructor:"LearnoHub", category:"Science", duration:"2h 30m", videoUrl:"https://www.youtube.com/embed/URUJD5NEXC8", thumbnail:"https://img.youtube.com/vi/URUJD5NEXC8/maxresdefault.jpg", whatYouLearn:["Types of microorganisms","Useful microorganisms","Harmful microorganisms","Food preservation","Antibiotics","Nitrogen cycle"], quiz:[] },
  { title:"Class 8 Science — Force and Pressure", description:"Learn about force, types of forces, pressure, atmospheric pressure, and their applications in everyday life.", instructor:"ExamFear Education", category:"Science", duration:"2h 00m", videoUrl:"https://www.youtube.com/embed/b1t41Q3xRM8", thumbnail:"https://img.youtube.com/vi/b1t41Q3xRM8/maxresdefault.jpg", whatYouLearn:["Force and its effects","Contact and non-contact forces","Pressure definition","Atmospheric pressure","Liquid pressure","Applications"], quiz:[] },
  { title:"Class 8 English — Writing Skills", description:"Improve Class 8 English writing with paragraph writing, letter writing, story writing, and grammar as per CBSE curriculum.", instructor:"Edumantra", category:"Language", duration:"3h 00m", videoUrl:"https://www.youtube.com/embed/0G3_kG5FFfQ", thumbnail:"https://img.youtube.com/vi/0G3_kG5FFfQ/maxresdefault.jpg", whatYouLearn:["Paragraph writing","Formal and informal letters","Story writing with hints","Notice writing","Grammar: adjectives and adverbs","Comprehension practice"], quiz:[] },
  { title:"Class 8 Social Science — Resources", description:"Study natural resources, types of resources, land resources, water resources, and their conservation as per NCERT Class 8 Geography.", instructor:"Magnet Brains", category:"General", duration:"3h 30m", videoUrl:"https://www.youtube.com/embed/wOclF9eP5OM", thumbnail:"https://img.youtube.com/vi/wOclF9eP5OM/maxresdefault.jpg", whatYouLearn:["Types of natural resources","Land resources and land use","Soil resources","Water resources","Mineral and power resources","Conservation"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // CLASS 9
  // ══════════════════════════════════════════════════════════
  { title:"Class 9 Mathematics (NCERT)", description:"Complete Class 9 Mathematics covering number systems, polynomials, coordinate geometry, linear equations, Euclid's geometry, triangles, quadrilaterals, circles, surface areas, volumes, and statistics.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"24h 00m", videoUrl:T.math.url, thumbnail:T.math.thumb, whatYouLearn:["Number systems and irrational numbers","Polynomials and factorisation","Coordinate geometry","Linear equations in two variables","Triangles and quadrilaterals","Surface areas and volumes"], quiz:[] },
  { title:"Class 9 Science (NCERT)", description:"Complete Class 9 Science covering matter, atoms and molecules, structure of atom, the fundamental unit of life, tissues, motion, force and Newton's laws, gravitation, and sound.", instructor:"NCERT Expert Faculty", category:"Science", duration:"22h 00m", videoUrl:T.science.url, thumbnail:T.science.thumb, whatYouLearn:["Matter in our surroundings","Atoms and molecules","Structure of the atom","Cell — fundamental unit of life","Motion, velocity and acceleration","Laws of motion and gravitation"], quiz:[] },
  { title:"Class 9 English (NCERT - Beehive)", description:"Complete Class 9 English based on Beehive and Moments. Includes all chapters with detailed explanations, grammar, writing skills, and board exam preparation.", instructor:"NCERT Expert Faculty", category:"Language", duration:"14h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["Beehive prose and poetry","Moments supplementary reader","Grammar: clauses and sentences","Formal letter and notice writing","Article and story writing","Board exam question patterns"], quiz:[] },
  { title:"Class 9 Hindi (NCERT - Kshitij & Sparsh)", description:"Class 9 Hindi covering Kshitij Part 1 and Sparsh. Complete chapter-wise explanations with grammar (sangya, sarvnam, ling, vachan) and writing practice.", instructor:"NCERT Expert Faculty", category:"Language", duration:"14h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Kshitij Part 1 chapters","Sparsh prose and poetry","Grammar: sangya, sarvnam, visheshan","Ling and vachan","Nibandh and patra lekhan","Apathit gadyansh"], quiz:[] },
  { title:"Class 9 Social Science (NCERT)", description:"Class 9 Social Science covering History (India and the Contemporary World I), Geography (Contemporary India I), Civics (Democratic Politics I), and Economics.", instructor:"NCERT Expert Faculty", category:"History", duration:"20h 00m", videoUrl:T.sst.url, thumbnail:T.sst.thumb, whatYouLearn:["French Revolution and socialism","Nazism and the rise of Hitler","Forest society and colonialism","Physical features of India","Climate and natural vegetation","Electoral politics and democracy"], quiz:[] },
  { title:"Class 9 Computer Science (CBSE)", description:"Introduction to computers, operating systems, MS Office, internet basics, and Python programming fundamentals as per CBSE Class 9 curriculum.", instructor:"CBSE Expert Faculty", category:"Programming", duration:"16h 00m", videoUrl:T.cs.url, thumbnail:T.cs.thumb, whatYouLearn:["Introduction to computers","Windows operating system","MS Word, Excel, PowerPoint","Internet and email basics","Introduction to Python","Basic Python programs"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // CLASS 10
  // ══════════════════════════════════════════════════════════
  { title:"Class 10 Mathematics (NCERT) — Board Exam Prep", description:"Complete Class 10 Mathematics covering real numbers, polynomials, pair of equations, quadratic equations, AP, triangles, coordinate geometry, trigonometry, circles, mensuration, statistics, and probability.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"30h 00m", videoUrl:T.math.url, thumbnail:T.math.thumb, whatYouLearn:["Real numbers and Euclid's lemma","Polynomials and zeroes","Quadratic equations","Arithmetic progressions","Trigonometry and applications","Statistics and probability"], quiz:[] },
  { title:"Class 10 Science (NCERT) — Board Exam Prep", description:"Complete Class 10 Science covering chemical reactions, acids and bases, metals, carbon compounds, life processes, control and coordination, electricity, magnetic effects, and our environment.", instructor:"NCERT Expert Faculty", category:"Science", duration:"28h 00m", videoUrl:T.science.url, thumbnail:T.science.thumb, whatYouLearn:["Chemical reactions and equations","Acids, bases and salts","Metals and non-metals","Life processes in plants and animals","Electricity and magnetic effects","Sustainable management of resources"], quiz:[] },
  { title:"Class 10 English (NCERT) — First Flight & Footprints", description:"Complete Class 10 English based on First Flight and Footprints Without Feet. Board exam-focused with grammar, letter writing, comprehension, and all chapter explanations.", instructor:"NCERT Expert Faculty", category:"Language", duration:"16h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["First Flight prose and poetry","Footprints Without Feet stories","Grammar: modals, clauses, determiners","Formal and informal letter writing","Speech and debate writing","Board exam answer techniques"], quiz:[] },
  { title:"Class 10 Hindi (NCERT - Kshitij & Sparsh)", description:"Complete Class 10 Hindi covering Kshitij Part 2 and Sparsh with detailed summaries, meanings, and grammar. Fully board exam oriented with model question papers.", instructor:"NCERT Expert Faculty", category:"Language", duration:"16h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Kshitij Part 2 chapters and kavitayen","Sparsh gadya and padya","Grammar: ras, chhand, alankar","Nibandh, patra and sandesh lekhan","Apathit gadyansh and kavyansh","Board model papers"], quiz:[] },
  { title:"Class 10 Social Science (NCERT) — Board Exam Prep", description:"Complete Class 10 Social Science covering History, Geography, Civics (Democratic Politics II), and Economics.", instructor:"NCERT Expert Faculty", category:"History", duration:"24h 00m", videoUrl:T.sst.url, thumbnail:T.sst.thumb, whatYouLearn:["Nationalism in India and Europe","Industrialisation and print culture","Resources and agriculture in India","Manufacturing industries","Power sharing and federalism","Development and money and credit"], quiz:[] },
  { title:"Class 10 Computer Applications (CBSE)", description:"Complete Class 10 Computer Applications covering Python programming, SQL databases, HTML basics, and digital literacy as per CBSE curriculum.", instructor:"CBSE Expert Faculty", category:"Programming", duration:"18h 00m", videoUrl:T.cs.url, thumbnail:T.cs.thumb, whatYouLearn:["Python: data types and operators","Python: loops and functions","Python: lists, tuples and dictionaries","SQL basics and queries","HTML and web page creation","Cyber safety and digital literacy"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // CLASS 11
  // ══════════════════════════════════════════════════════════
  { title:"Class 11 Mathematics (NCERT)", description:"Complete Class 11 Mathematics covering sets, relations, trigonometry, complex numbers, sequences, straight lines, conic sections, 3D geometry, limits, derivatives, statistics, and probability.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"36h 00m", videoUrl:T.calculus.url, thumbnail:T.calculus.thumb, whatYouLearn:["Sets, relations and functions","Trigonometric functions","Complex numbers and quadratic equations","Permutations and combinations","Binomial theorem and sequences","Limits, derivatives and probability"], quiz:[] },
  { title:"Class 11 Physics (NCERT)", description:"Complete Class 11 Physics covering units and measurements, kinematics, laws of motion, work and energy, rotational motion, gravitation, thermodynamics, oscillations, and waves.", instructor:"NCERT Expert Faculty", category:"Science", duration:"38h 00m", videoUrl:T.physics.url, thumbnail:T.physics.thumb, whatYouLearn:["Units, dimensions and measurements","Kinematics: motion in 1D and 2D","Laws of motion (Newton's laws)","Work, energy and power","Rotational motion and moment of inertia","Thermodynamics and kinetic theory"], quiz:[] },
  { title:"Class 11 Chemistry (NCERT)", description:"Complete Class 11 Chemistry covering basic concepts, atomic structure, periodic table, chemical bonding, states of matter, thermodynamics, equilibrium, redox, hydrogen, s-block, and organic chemistry.", instructor:"NCERT Expert Faculty", category:"Science", duration:"36h 00m", videoUrl:T.chemistry.url, thumbnail:T.chemistry.thumb, whatYouLearn:["Basic concepts of chemistry and mole","Atomic structure and periodic table","Chemical bonding (VSEPR, MOT)","States of matter: gases and liquids","Thermodynamics and equilibrium","Hydrocarbons and basic organic chemistry"], quiz:[] },
  { title:"Class 11 Biology (NCERT)", description:"Complete Class 11 Biology covering the living world, biological classification, plant and animal kingdom, cell, biomolecules, cell cycle, transport, mineral nutrition, and breathing.", instructor:"NCERT Expert Faculty", category:"Science", duration:"34h 00m", videoUrl:T.biology.url, thumbnail:T.biology.thumb, whatYouLearn:["Living world and biological classification","Plant and animal kingdom","Cell structure and organelles","Biomolecules and enzymes","Cell cycle and cell division","Photosynthesis and respiration in plants"], quiz:[] },
  { title:"Class 11 English (NCERT - Hornbill & Snapshots)", description:"Complete Class 11 English based on Hornbill and Snapshots. Covers all chapters with grammar, writing skills, and tips for scoring high in CBSE board exams.", instructor:"NCERT Expert Faculty", category:"Language", duration:"14h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["Hornbill prose and poetry chapters","Snapshots supplementary reader","Grammar: reported speech, modals","Essay, debate and speech writing","Notice, poster and advertisement","Comprehension and analysis skills"], quiz:[] },
  { title:"Class 11 Hindi (NCERT - Aroh & Vitan)", description:"Complete Class 11 Hindi covering Aroh Part 1 and Vitan Part 1. Chapter summaries, meanings, and grammar for board exam preparation.", instructor:"NCERT Expert Faculty", category:"Language", duration:"14h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Aroh Part 1 gadya and padya","Vitan Part 1 chapters","Grammar: upsarg, pratyay, samaas","Muhavare and lokoktiyan","Nibandh and patra lekhan","Apathit gadyansh practice"], quiz:[] },
  { title:"Class 11 Accountancy (NCERT)", description:"Complete Class 11 Accountancy covering introduction to accounting, journal, ledger, trial balance, bank reconciliation, depreciation, and financial statements.", instructor:"NCERT Expert Faculty", category:"Business", duration:"28h 00m", videoUrl:T.accounts.url, thumbnail:T.accounts.thumb, whatYouLearn:["Introduction to accounting","Journal and ledger entries","Trial balance and rectification","Bank reconciliation statement","Depreciation and provisions","Financial statements of sole proprietorship"], quiz:[] },
  { title:"Class 11 Business Studies (NCERT)", description:"Complete Class 11 Business Studies covering nature of business, forms of business organisation, public and private enterprises, business services, and emerging modes of business.", instructor:"NCERT Expert Faculty", category:"Business", duration:"20h 00m", videoUrl:T.business.url, thumbnail:T.business.thumb, whatYouLearn:["Nature and purpose of business","Forms of business organisation","Public, private and global enterprises","Business services and trade","E-business and outsourcing","Social responsibility of business"], quiz:[] },
  { title:"Class 11 Economics (NCERT)", description:"Complete Class 11 Economics covering Indian Economic Development (Part A) and Statistics for Economics (Part B) as per NCERT/CBSE syllabus.", instructor:"NCERT Expert Faculty", category:"Business", duration:"22h 00m", videoUrl:T.economics.url, thumbnail:T.economics.thumb, whatYouLearn:["Indian economy on the eve of independence","Economic planning and reforms","Agriculture and rural economy","Collection and organisation of data","Measures of central tendency","Index numbers and correlation"], quiz:[] },
  { title:"Class 11 Computer Science — Python (CBSE)", description:"Complete Class 11 Computer Science covering Python programming, data structures, database concepts, and networking as per CBSE 2024-25 syllabus.", instructor:"CBSE Expert Faculty", category:"Programming", duration:"24h 00m", videoUrl:T.cs.url, thumbnail:T.cs.thumb, whatYouLearn:["Python fundamentals and data types","Control flow: if, for, while","Strings, lists, tuples and dictionaries","Functions and modules","File handling in Python","Basics of DBMS and SQL"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // CLASS 12
  // ══════════════════════════════════════════════════════════
  { title:"Class 12 Mathematics (NCERT) — Board Exam Prep", description:"Complete Class 12 Mathematics covering relations and functions, inverse trigonometry, matrices, determinants, continuity, differentiation, integration, differential equations, vectors, 3D geometry, linear programming, and probability.", instructor:"NCERT Expert Faculty", category:"Mathematics", duration:"44h 00m", videoUrl:T.calculus.url, thumbnail:T.calculus.thumb, whatYouLearn:["Relations, functions and inverse trigonometry","Matrices and determinants","Continuity, differentiability and applications","Integration: indefinite and definite","Differential equations","Vectors, 3D geometry, LP and probability"], quiz:[] },
  { title:"Class 12 Physics (NCERT) — Board Exam Prep", description:"Complete Class 12 Physics covering electrostatics, current electricity, magnetic effects, electromagnetic induction, EMW, optics, dual nature, atoms, nuclei, and semiconductors.", instructor:"NCERT Expert Faculty", category:"Science", duration:"42h 00m", videoUrl:T.physics.url, thumbnail:T.physics.thumb, whatYouLearn:["Electrostatics and capacitors","Current electricity and circuits","Magnetic effects and moving charges","Electromagnetic induction and AC","Ray optics and wave optics","Semiconductors and communication systems"], quiz:[] },
  { title:"Class 12 Chemistry (NCERT) — Board Exam Prep", description:"Complete Class 12 Chemistry covering solid state, solutions, electrochemistry, kinetics, surface chemistry, p/d/f block, coordination compounds, haloalkanes, alcohols, aldehydes, amines, and biomolecules.", instructor:"NCERT Expert Faculty", category:"Science", duration:"40h 00m", videoUrl:T.chemistry.url, thumbnail:T.chemistry.thumb, whatYouLearn:["Solid state and solutions","Electrochemistry and chemical kinetics","d and f block elements and coordination compounds","Haloalkanes and haloarenes","Alcohols, phenols and ethers","Amines, polymers and biomolecules"], quiz:[] },
  { title:"Class 12 Biology (NCERT) — Board Exam Prep", description:"Complete Class 12 Biology covering reproduction, genetics, evolution, human health, biotechnology, ecology, and biodiversity as per NCERT and CBSE board exam pattern.", instructor:"NCERT Expert Faculty", category:"Science", duration:"38h 00m", videoUrl:T.biology.url, thumbnail:T.biology.thumb, whatYouLearn:["Sexual reproduction in plants and animals","Principles of inheritance and variation","Molecular basis of inheritance (DNA/RNA)","Evolution and origin of life","Human health and disease","Biotechnology and its applications"], quiz:[] },
  { title:"Class 12 English (NCERT - Flamingo & Vistas)", description:"Complete Class 12 English based on Flamingo and Vistas. Board exam-oriented with all chapter explanations, grammar, writing skills, and sample papers.", instructor:"NCERT Expert Faculty", category:"Language", duration:"16h 00m", videoUrl:T.english.url, thumbnail:T.english.thumb, whatYouLearn:["Flamingo prose and poetry","Vistas supplementary reader","Grammar: transformation and editing","Formal letter and report writing","Article, speech and debate writing","CBSE board exam strategy"], quiz:[] },
  { title:"Class 12 Hindi (NCERT - Aroh & Vitan)", description:"Complete Class 12 Hindi covering Aroh Part 2 and Vitan Part 2. Chapter-wise explanations, grammar, and model question papers for CBSE board exams.", instructor:"NCERT Expert Faculty", category:"Language", duration:"16h 00m", videoUrl:T.hindi.url, thumbnail:T.hindi.thumb, whatYouLearn:["Aroh Part 2 gadya and kavita","Vitan Part 2 chapters","Grammar: vakya bhed and sandhi","Muhavare and lokoktiyan","Anuched, nibandh and patra lekhan","Board model papers and tips"], quiz:[] },
  { title:"Class 12 Accountancy (NCERT) — Board Exam Prep", description:"Complete Class 12 Accountancy covering partnership accounts, company accounts, analysis of financial statements, and cash flow statements as per CBSE board exam pattern.", instructor:"NCERT Expert Faculty", category:"Business", duration:"32h 00m", videoUrl:T.accounts.url, thumbnail:T.accounts.thumb, whatYouLearn:["Partnership: fundamentals and goodwill","Admission, retirement and death of partner","Dissolution of partnership firm","Issue and forfeiture of shares and debentures","Analysis of financial statements","Cash flow statement"], quiz:[] },
  { title:"Class 12 Business Studies (NCERT) — Board Exam Prep", description:"Complete Class 12 Business Studies covering nature of management, planning, organising, staffing, directing, controlling, financial management, marketing, and consumer protection.", instructor:"NCERT Expert Faculty", category:"Business", duration:"24h 00m", videoUrl:T.business.url, thumbnail:T.business.thumb, whatYouLearn:["Nature and significance of management","Planning and organising","Staffing and directing","Controlling and coordination","Financial management and markets","Marketing management and consumer protection"], quiz:[] },
  { title:"Class 12 Economics (NCERT) — Board Exam Prep", description:"Complete Class 12 Economics covering Introductory Macroeconomics (Part A) and Indian Economic Development (Part B) as per CBSE board exam.", instructor:"NCERT Expert Faculty", category:"Business", duration:"26h 00m", videoUrl:T.economics.url, thumbnail:T.economics.thumb, whatYouLearn:["National income and its measurement","Money, banking and credit creation","Aggregate demand, supply and equilibrium","Government budget and fiscal policy","Balance of payments and exchange rate","Indian economic development post-1991"], quiz:[] },
  { title:"Class 12 Computer Science — Python & DBMS (CBSE)", description:"Complete Class 12 Computer Science covering advanced Python, data structures, computer networks, MySQL databases, and interface of Python with SQL as per CBSE 2024-25.", instructor:"CBSE Expert Faculty", category:"Programming", duration:"28h 00m", videoUrl:T.cs.url, thumbnail:T.cs.thumb, whatYouLearn:["Python: functions, recursion and modules","Data structures: stack, queue, linked list","Computer networks and protocols","MySQL and database concepts","Python-MySQL connectivity","Society, law and ethics in computing"], quiz:[] },
  { title:"Class 12 Geography (NCERT)", description:"Complete Class 12 Geography covering Fundamentals of Human Geography (Part A) and India: People and Economy (Part B) as per CBSE board exam pattern.", instructor:"NCERT Expert Faculty", category:"General", duration:"20h 00m", videoUrl:T.geo.url, thumbnail:T.geo.thumb, whatYouLearn:["Human geography and population","Migration and human development","Primary, secondary and tertiary activities","Transport and communication","India: population and settlements","Land resources and water resources in India"], quiz:[] },
  { title:"Class 12 History (NCERT - Themes in Indian History)", description:"Complete Class 12 History covering all 15 themes from Themes in Indian History Parts I, II, and III as per CBSE board exam with source-based questions.", instructor:"NCERT Expert Faculty", category:"History", duration:"22h 00m", videoUrl:T.history.url, thumbnail:T.history.thumb, whatYouLearn:["Bricks, beads and bones (Harappan civilisation)","Kings, farmers and towns","Kinship, caste and class","Bhakti and Sufi traditions","Rebels and the Raj (1857)","Mahatma Gandhi and the nationalist movement"], quiz:[] },
  { title:"Class 12 Political Science (NCERT)", description:"Complete Class 12 Political Science covering Contemporary World Politics (Part A) and Politics in India since Independence (Part B) as per NCERT/CBSE.", instructor:"NCERT Expert Faculty", category:"General", duration:"20h 00m", videoUrl:T.polsci.url, thumbnail:T.polsci.thumb, whatYouLearn:["Cold War era and its impact","Disintegration of USSR and globalisation","US hegemony in world politics","India's foreign policy and security","Nation building and partition challenges","Coalition politics and recent developments"], quiz:[] },

  // ══════════════════════════════════════════════════════════
  // JEE / NEET PREPARATION
  // ══════════════════════════════════════════════════════════
  { title:"JEE Mains Mathematics — Complete Preparation", description:"Comprehensive JEE Mains Mathematics covering all topics with 1000+ solved problems, shortcuts, and previous year paper analysis.", instructor:"IIT Alumni Faculty", category:"Mathematics", duration:"60h 00m", videoUrl:T.jee.url, thumbnail:T.jee.thumb, whatYouLearn:["Coordinate geometry (straight lines, circles, conics)","Calculus (limits, derivatives, integrals)","Algebra (matrices, determinants, permutations)","Trigonometry and inverse trig","3D geometry and vectors","Statistics and probability"], quiz:[] },
  { title:"JEE Mains Physics — Complete Preparation", description:"Comprehensive JEE Mains Physics with concept-based explanations, numerical problem solving, and chapter-wise previous year analysis.", instructor:"IIT Alumni Faculty", category:"Science", duration:"60h 00m", videoUrl:T.physics.url, thumbnail:T.physics.thumb, whatYouLearn:["Mechanics: laws of motion, work-energy","Rotational dynamics and gravitation","Thermodynamics and kinetic theory","Electrostatics, current and magnetism","EMI, AC circuits and optics","Modern physics: atoms, nuclei, semiconductors"], quiz:[] },
  { title:"JEE Mains Chemistry — Complete Preparation", description:"Comprehensive JEE Mains Chemistry covering Physical, Inorganic, and Organic Chemistry with numericals and mnemonics.", instructor:"IIT Alumni Faculty", category:"Science", duration:"56h 00m", videoUrl:T.chemistry.url, thumbnail:T.chemistry.thumb, whatYouLearn:["Physical chemistry: thermodynamics, kinetics, equilibrium","Atomic structure, periodic table and bonding","s, p, d and f block elements","Organic mechanisms: addition, substitution","Functional group chemistry","Biomolecules and polymers"], quiz:[] },
  { title:"JEE Advanced Mathematics — Problem Solving", description:"Advanced-level JEE Mathematics with olympiad-style problems, IIT previous year papers, and advanced calculus, complex numbers, and 3D geometry.", instructor:"IIT JEE Top Ranker Faculty", category:"Mathematics", duration:"72h 00m", videoUrl:T.jee.url, thumbnail:T.jee.thumb, whatYouLearn:["Advanced calculus problems","Complex numbers and advanced algebra","Advanced coordinate geometry","Vector and 3D advanced problems","Probability and combinations (advanced)","IIT JEE previous year paper analysis"], quiz:[] },
  { title:"NEET Biology — Complete Preparation", description:"Complete NEET Biology preparation covering Class 11 and 12 NCERT Biology with special focus on previous year NEET questions and diagram-based questions.", instructor:"NEET Expert Faculty", category:"Science", duration:"64h 00m", videoUrl:T.neet.url, thumbnail:T.neet.thumb, whatYouLearn:["Cell biology and biomolecules","Plant physiology in detail","Human physiology: all systems","Reproduction and developmental biology","Genetics, evolution and molecular biology","Ecology, biodiversity and biotechnology"], quiz:[] },
  { title:"NEET Chemistry — Complete Preparation", description:"Complete NEET Chemistry preparation with NCERT-based theory, numerical problems, and previous year NEET question bank analysis.", instructor:"NEET Expert Faculty", category:"Science", duration:"52h 00m", videoUrl:T.chemistry.url, thumbnail:T.chemistry.thumb, whatYouLearn:["Basic concepts, mole and atomic structure","Periodic table and chemical bonding","States of matter and thermodynamics","Equilibrium, redox and electrochemistry","Organic chemistry: mechanisms and reactions","Biomolecules, polymers and everyday chemistry"], quiz:[] },
  { title:"NEET Physics — Complete Preparation", description:"Complete NEET Physics covering all chapters from Class 11 and 12 with NCERT-based theory and NEET-style MCQ practice.", instructor:"NEET Expert Faculty", category:"Science", duration:"50h 00m", videoUrl:T.physics.url, thumbnail:T.physics.thumb, whatYouLearn:["Mechanics and rotational motion","Properties of matter and thermodynamics","Oscillations, waves and SHM","Electrostatics and current electricity","Optics: ray and wave","Modern physics and semiconductor devices"], quiz:[] },
  { title:"CBSE Board Exam Preparation — Class 10 (All Subjects)", description:"Focused CBSE Class 10 board exam preparation covering Mathematics, Science, English, Hindi, and Social Science with model papers and exam tips.", instructor:"CBSE Expert Faculty", category:"General", duration:"40h 00m", videoUrl:T.general.url, thumbnail:T.general.thumb, whatYouLearn:["Mathematics revision and model papers","Science chapter-wise important questions","English grammar and writing tips","Hindi vyakaran and lekhan","Social Science map work and source questions","Time management and exam strategy"], quiz:[] },
  { title:"CBSE Board Exam Preparation — Class 12 (All Subjects)", description:"Focused CBSE Class 12 board exam preparation with revision notes, previous year papers, and expert tips for all subjects.", instructor:"CBSE Expert Faculty", category:"General", duration:"48h 00m", videoUrl:T.general.url, thumbnail:T.general.thumb, whatYouLearn:["Physics important derivations and numericals","Chemistry reaction revision and name reactions","Mathematics important theorems and integration","Biology diagrams and value-based questions","English board-pattern writing tasks","Exam strategy and stress management"], quiz:[] },
];

async function seed() {
  try {
    console.log("🔌 Connecting to MongoDB...");
    await mongoose.connect(MONGO_URI);
    console.log("✅ Connected!\n");

    // ── Delete old school courses first so thumbnails get updated ──
    console.log("🗑️  Removing old school courses to update thumbnails...");
    const deleted = await Course.deleteMany({
      title: { $regex: /^Class (7|8|9|10|11|12)|^JEE|^NEET|^CBSE Board/i }
    });
    console.log(`   Removed ${deleted.deletedCount} old courses\n`);

    let inserted = 0;
    for (const course of SCHOOL_COURSES) {
      await Course.create(course);
      console.log(`  ✅ Added: ${course.title}`);
      inserted++;
    }

    const total = await Course.countDocuments();
    console.log(`\n${"═".repeat(65)}`);
    console.log(`🎉 School courses seeding complete!`);
    console.log(`   ✅ Added   : ${inserted} courses with correct thumbnails`);
    console.log(`   📚 Total   : ${total} courses in database`);
    console.log(`${"═".repeat(65)}\n`);
    process.exit(0);
  } catch (err) {
    console.error("❌ Error:", err.message);
    process.exit(1);
  }
}

seed();
